# title: Luigi Emanuele Zippo
# logo: Assets/profilepic.png
# description: text below image
# show_downloads: true 
# theme: jekyll-theme-minimal

# <a href="lezippo.github.io/Curriculum.pdf" target="_blank">PDF</a>

<embed src="https://lezippo.github.io/Curriculum.pdf" type="application/pdf" />

